features:
  - month
  - horse_id
  - jockey_id
  - trainer_id
  - wakuban
  - umaban
  - sex
  - age
  - weight
  - weight_diff
  - tansho_odds
  # - popularity
  - impost
  - race_type
  - around
  - course_len
  - weather
  - ground_state
  - race_class
  - place
  - Turf_Suitability
  - Distance_Preference
  - Front-Running
  - Early_Maturity
  - Heavy_Track
  - relative_distance
  - relative_front
  - rank_mean_1races_relative
  - rank_median_1races_relative
  - rank_max_1races_relative
  - rank_min_1races_relative
  - prize_mean_1races_relative
  - prize_median_1races_relative
  - prize_max_1races_relative
  - prize_min_1races_relative
  - rank_diff_mean_1races_relative
  - rank_diff_median_1races_relative
  - rank_diff_max_1races_relative
  - rank_diff_min_1races_relative
  - race_class_mean_1races_relative
  - race_class_median_1races_relative
  - race_class_max_1races_relative
  - race_class_min_1races_relative
  - rank_furlongs_mean_1races_relative
  - rank_furlongs_median_1races_relative
  - rank_furlongs_max_1races_relative
  - rank_furlongs_min_1races_relative
  - rank_1races_mean
  - prize_1races_mean
  - rank_diff_1races_mean
  - race_class_1races_mean
  - rank_mean_3races_relative
  - rank_median_3races_relative
  - rank_max_3races_relative
  - rank_min_3races_relative
  - prize_mean_3races_relative
  - prize_median_3races_relative
  - prize_max_3races_relative
  - prize_min_3races_relative
  - rank_diff_mean_3races_relative
  - rank_diff_median_3races_relative
  - rank_diff_max_3races_relative
  - rank_diff_min_3races_relative
  - race_class_mean_3races_relative
  - race_class_median_3races_relative
  - race_class_max_3races_relative
  - race_class_min_3races_relative
  - rank_furlongs_mean_3races_relative
  - rank_furlongs_median_3races_relative
  - rank_furlongs_max_3races_relative
  - rank_furlongs_min_3races_relative
  - rank_3races_mean
  - prize_3races_mean
  - rank_diff_3races_mean
  - race_class_3races_mean
  - rank_mean_5races_relative
  - rank_median_5races_relative
  - rank_max_5races_relative
  - rank_min_5races_relative
  - prize_mean_5races_relative
  - prize_median_5races_relative
  - prize_max_5races_relative
  - prize_min_5races_relative
  - rank_diff_mean_5races_relative
  - rank_diff_median_5races_relative
  - rank_diff_max_5races_relative
  - rank_diff_min_5races_relative
  - race_class_mean_5races_relative
  - race_class_median_5races_relative
  - race_class_max_5races_relative
  - race_class_min_5races_relative
  - rank_furlongs_mean_5races_relative
  - rank_furlongs_median_5races_relative
  - rank_furlongs_max_5races_relative
  - rank_furlongs_min_5races_relative
  - rank_5races_mean
  - prize_5races_mean
  - rank_diff_5races_mean
  - race_class_5races_mean
  - rank_mean_10races_relative
  - rank_median_10races_relative
  - rank_max_10races_relative
  - rank_min_10races_relative
  - prize_mean_10races_relative
  - prize_median_10races_relative
  - prize_max_10races_relative
  - prize_min_10races_relative
  - rank_diff_mean_10races_relative
  - rank_diff_median_10races_relative
  - rank_diff_max_10races_relative
  - rank_diff_min_10races_relative
  - race_class_mean_10races_relative
  - race_class_median_10races_relative
  - race_class_max_10races_relative
  - race_class_min_10races_relative
  - rank_furlongs_mean_10races_relative
  - rank_furlongs_median_10races_relative
  - rank_furlongs_max_10races_relative
  - rank_furlongs_min_10races_relative
  - rank_10races_mean
  - prize_10races_mean
  - rank_diff_10races_mean
  - race_class_10races_mean
  - rank_mean_1000races_relative
  - rank_median_1000races_relative
  - rank_max_1000races_relative
  - rank_min_1000races_relative
  - prize_mean_1000races_relative
  - prize_median_1000races_relative
  - prize_max_1000races_relative
  - prize_min_1000races_relative
  - rank_diff_mean_1000races_relative
  - rank_diff_median_1000races_relative
  - rank_diff_max_1000races_relative
  - rank_diff_min_1000races_relative
  - race_class_mean_1000races_relative
  - race_class_median_1000races_relative
  - race_class_max_1000races_relative
  - race_class_min_1000races_relative
  - rank_furlongs_mean_1000races_relative
  - rank_furlongs_median_1000races_relative
  - rank_furlongs_max_1000races_relative
  - rank_furlongs_min_1000races_relative
  - rank_1000races_mean
  - prize_1000races_mean
  - rank_diff_1000races_mean
  - race_class_1000races_mean
  - rank_furlongs_1races_mean
  - rank_furlongs_3races_mean
  - rank_furlongs_5races_mean
  - rank_furlongs_10races_mean
  - rank_furlongs_1000races_mean